name: 05 - 1 - Event Filters and Activity Types

on:
    pull_request: 
        types: 
            - opened
            - synchronize
        branches:
            - main

jobs:
    announce:
        runs-on: ubuntu-latest
        steps:
            - name: Announce Start of PR
              run: echo "PR Checks Commencing"
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/my-vue-app
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: Setup Node
              run: npm ci
            - name : Run Unit Test
              run: npm run test  
