name: 05 - 1 - Event Filters and Activity Types

on:
    pull_request: 
        types: 
            - closed
        branches:
            - main

jobs:
    announce:
        runs-on: ubuntu-latest
        steps:
            - name: Announce Close of PR
              run: echo "PR Has been successfully Closed"
